package com.creants.creants_2x.core.setting;

/**
 * @author LamHM
 *
 */
public enum QAntRoomSettings {
	ROOM_NAME_CHANGE("ROOM_NAME_CHANGE", 0),
	PASSWORD_STATE_CHANGE("PASSWORD_STATE_CHANGE", 1),
	PUBLIC_MESSAGES("PUBLIC_MESSAGES", 2),
	CAPACITY_CHANGE("CAPACITY_CHANGE", 3),
	USER_ENTER_EVENT("USER_ENTER_EVENT", 4),
	USER_EXIT_EVENT("USER_EXIT_EVENT", 5),
	USER_COUNT_CHANGE_EVENT("USER_COUNT_CHANGE_EVENT", 6),
	USER_VARIABLES_UPDATE_EVENT("USER_VARIABLES_UPDATE_EVENT", 7);

	private QAntRoomSettings(String eventName, int id) {
	}
}
