package com.creants.creants_2x.core;

/**
 * @author LamHM
 *
 */
public enum QAntEventType {
	SERVER_READY("SERVER_READY", 0),
	USER_LOGIN("USER_LOGIN", 1),
	USER_JOIN_ZONE("USER_JOIN_ZONE", 2),
	USER_LOGOUT("USER_LOGOUT", 3),
	USER_JOIN_ROOM("USER_JOIN_ROOM", 4),
	USER_LEAVE_ROOM("USER_LEAVE_ROOM", 5),
	USER_DISCONNECT("USER_DISCONNECT", 6),
	USER_RECONNECTION_TRY("USER_RECONNECTION_TRY", 7),
	USER_RECONNECTION_SUCCESS("USER_RECONNECTION_SUCCESS", 8),
	ROOM_ADDED("ROOM_ADDED", 9),
	ROOM_REMOVED("ROOM_REMOVED", 10),
	PUBLIC_MESSAGE("PUBLIC_MESSAGE", 11),
	PRIVATE_MESSAGE("PRIVATE_MESSAGE", 12),
	ROOM_VARIABLES_UPDATE("ROOM_VARIABLES_UPDATE", 13),
	USER_VARIABLES_UPDATE("USER_VARIABLES_UPDATE", 14),
	SPECTATOR_TO_PLAYER("SPECTATOR_TO_PLAYER", 15),
	PLAYER_TO_SPECTATOR("PLAYER_TO_SPECTATOR", 16),
	BUDDY_ADD("BUDDY_ADD", 17),
	BUDDY_REMOVE("BUDDY_REMOVE", 18),
	BUDDY_BLOCK("BUDDY_BLOCK", 19),
	BUDDY_VARIABLES_UPDATE("BUDDY_VARIABLES_UPDATE", 20),
	BUDDY_ONLINE_STATE_UPDATE("BUDDY_ONLINE_STATE_UPDATE", 21),
	BUDDY_MESSAGE("BUDDY_MESSAGE", 22),
	BUDDY_LIST_INIT("BUDDY_LIST_INIT", 23),
	GAME_INVITATION_SUCCESS("GAME_INVITATION_SUCCESS", 24),
	GAME_INVITATION_FAILURE("GAME_INVITATION_FAILURE", 25),
	FILE_UPLOAD("FILE_UPLOAD", 26),
	__TRACE_MESSAGE("__TRACE_MESSAGE", 27),
	__GRID_NODE_BECOMES_MASTER("__GRID_NODE_BECOMES_MASTER", 28);

	private QAntEventType(String eventName, int id) {
	}
}
